### ISSUE TITLE
(zigbee) device wird ignoriert

### ISSUE THREAD

**Issue by dirkhe** [ioBroker/ioBroker.type-detector#2]
Der zigbee Adapter legt die Objekte als device nach dem Schema zigbee.0.7cb03eaa00a94dc3.state an. Die Funktion getAllStatesInDevice() findet aber die states nicht, weil die regex eine Ebene mehr erwartet. Wenn ich das ändere zu 
var reg = new RegExp('^' + channelId.replace(/\./g, '\\.') + '\\.[^.]+(\\.[^.]+)?$'); 
finde ich auch meine zigbee. Ich könnte zwar hingehen und alle devices zu channel ändern, aber eigentlich denke ich, dass device ja richtig ist, oder?

**Comment by Apollon77** [comment]
Ne Ist es nicht ;-) da muss der types detector wohl intelligenter suchen.

**Comment by dirkhe** [comment]
Deinen Kommentar verstehe ich nicht so ganz. Wenn der zigbee Adapter das falsch macht, müsste man das ja da ändern. Aber es gibt ja auch genug andere Objekte, wo der User selber Channel oder device auswählen muss und ich denke, dass da so mancher eine Lampe zb. Als Service sieht.
Mit dem geänderten regex wäre der letzte Part ja optional, das wäre ja schön ein wenig "intelligenter", oder?

**Comment by GermanBluefox** [comment]
Kannst du Baum hier Posten, damit ich die Vorstellung bekomme? Aktuell kann ich mir nicht so gut die Objekt-Struktur vorstellen.

**Comment by dirkhe** [comment]
![Screenshot_20190614-221134](https://user-images.githubusercontent.com/9537962/59535519-799b6380-8ef1-11e9-9f32-ab2295d75001.png)
Die werden ja durch den zugebe adapter automatisch erstellt

**Comment by Garfonso** [comment]
Dieses Issue sollte mal geschlossen werden, geht schon länger. :-)
