### ISSUE TITLE
Wrong object for Temperature Entity

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.type-detector#21]
**Describe the bug**  
For Homematic thermostats, the Temperature Entity points to an incorrect object. See the following example:
sensor.ThermostatBuero_Temperature hm-rpc.1.000A98A9A22E81.1.PARTY_SET_POINT_TEMPERATURE
Correct would be the object hm-rpc.1.000A98A9A22E81.1.ACTUAL_TEMPERATURE
If the temperature setpoint is also to be entered as an entity, the correct object would be: hm-rpc.1.000A98A9A22E81.1.SET_POINT_TEMPERATURE

**Screenshots & Logfiles**  
[hm-rpc.1.000A98A9A22E81.zip](https://github.com/ioBroker/ioBroker.type-detector/files/6761735/hm-rpc.1.000A98A9A22E81.zip)

**Versions:**  
 - JS-Controller version: 3.3.14
 - Node version: 14.16.1
 - Operating system: Docker Container

**Additional context**  
Nothing

**Comment by GermanBluefox** [comment]
The PARTY_SET_POINT_TEMPERATURE datapoint was removed from being to get the role: https://github.com/ioBroker/ioBroker.hm-rpc/commit/3ee20a2de2d4e61b20ba622d5c7da4b920cac945#diff-6ef04a9e675def1145dff7cc57420b1ea8bb3f6f5a5e4502cc5da0281981b472L306
But it works only for new created devices. For old devices, the role for PARTY_SET_POINT_TEMPERATURE must be delete manually via admin
