### ISSUE TITLE
ROLES: Timing Roles missing

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.type-detector#36]
I could not find any Role for

Time Difference (output/RO) type: number - value in ms 

Time Interverall (input/RW) Type number - value in ms
Timeout (input/RW) Type number - value in ms

The input values are normally "Level.xxx" Roles. But in generl I would suggest to discuss "Level" for input states which are not related to some physical level too. (Although I do not have a suggestions for the name, ev. a dedicated time.xxx ? Or something more general?)

**Comment by Garfonso** [comment]
This is solved, right? We should close it (somehow the commit message did not do its magic :-/ )

Or do we have devices that need the role already?

**Comment by mcm1957** [comment]
roles added to doc - correct.
So we can close here.
