### ISSUE TITLE
sonoff Light has 3 power switch

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.type-detector#5]
sonoff lights has 3 states with type power switch. type detector recognize the wrong one
https://forum.iobroker.net/assets/uploads/files/1565189289324-sonoff.0.wohnzimmergluehbirne.json

**Comment by Garfonso** [comment]
I saw this in a different situation, too (I think it was effect or something). Not really sure which way to go here...
Maybe best would be to try to change adapters to use "switch.light" or "switch.power" for on/off in the long run. So maybe add an issue in sonoff?

You can try to change the role of "POWER" to "switch.light" which should then be detected as "ON_LIGHT" and used as preferred state (at least in lovelace for example). Maybe that solves the issue already?

**Comment by GermanBluefox** [comment]
Just remove the role from the wrong one and that is all
