### ISSUE TITLE
deconz light has level.dimmer and level.dimspeed

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.type-detector#6]
deconz light has level.dimmer and level.dimspeed. the regex select everything with level as dimmer but chose the wrong one

https://forum.iobroker.net/assets/uploads/files/1567694061715-deconz.0.lights.json

**Comment by TA2k** [comment]
it has also color.temp this is ignored by type ct which search for
level\.color\.temperature$/,

**Comment by Apollon77** [comment]
second should be fixed in Adapter because many here are simply invalid/undefined roles
