### ISSUE TITLE
shelly brightness not recognized

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.type-detector#7]
shelly bulb rgb 
https://forum.iobroker.net/assets/uploads/files/1570047971757-shelly.1.shblb-1-421076-1.json

brightness has no id but there is a state with level.brightness
level.temperature is white instead of the state with level.temperature

**Comment by Garfonso** [comment]
can you test if the buld is now recognized as rgb device?

**Comment by Garfonso** [comment]
Since there was no reaction from OP for over a month, we should close the issue. My tests work fine with the white state added.
